version: '3.3'
services:
  api:
    stdin_open: true
    build:
        context: .
        dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
     - type: bind
       source: ./src
       target: /nestjs_sandbox/src
  web:
    image: docker.pkg.github.com/rarg22/github-actions-continuous-delivery/rarg22-aws-ttt:175
    ports: 
      - "80:80"