version: '3.3'
services:
  api:
    build:
        context: .
        dockerfile: ./docker/Dockerfile.dev
    container_name: mynestjs
    ports:
      - "5000:5000"
    volumes: 
     - type: bind
       source: ./src
       target: /nestjs_sandbox/src
  web:
    stdin_open: true
    image: docker.pkg.github.com/rarg22/reactjs-sandbox/reactjs-sandbox-develop:latest
    container_name: myreactjs
    ports: 
      - "3000:3000"
  db:
    image: amazon/dynamodb-local
    container_name: mydynamodb
    ports:
      - "8000:8000"