name: Develop Pull-Request Workflow

on:
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}
        restore-keys: -node-

    - name: Node Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build
    - run: npm run test