name: Master Push Workflow

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}
        restore-keys: -node-

    - name: Node Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - run: npm install
    - run: npm run build
    - run: npm run test

    - name: Upload Deployment Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: deployment-artifacts
        path: |
          dist
          package.json
          pacakage-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Download deployment artifacts
      uses: actions/download-artifact@v2
      with:
        name: deployment-artifacts

    - name: Generate deployment package
      run: npm run zip

    - uses: gerred/actions/current-time@master
      id: current-time

    - uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'

    - name: Deploy to AWS Beanstalk
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        application_name: ELB-Demo
        environment_name: ElbDemo-env
        region: us-east-2
        version_label: "elb-demo-master-${{ steps.format-time.outputs.replaced }}"
        deployment_package: deploy.zip

    - name: Deployed!
      run: echo Application Version-elb-demo-source-${{ steps.format-time.outputs.replaced }} deployed succesfully!

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: docker build -f "docker/Dockerfile.dev" -t docker.pkg.github.com/rarg22/nestjs-sandbox/master:latest .
    - run: docker login docker.pkg.github.com -u rarg22 -p ${{ secrets.GITHUB_TOKEN }}
    - run: docker push docker.pkg.github.com/rarg22/nestjs-sandbox/master:latest

    
